"""empty message

Revision ID: ca277f51404c
Revises: 57535f8d20f9
Create Date: 2020-02-09 13:10:14.376076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca277f51404c'
down_revision = '57535f8d20f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('desctiption', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'desctiption')
    # ### end Alembic commands ###
